on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: CI Tests
  
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.10", "3.11", "3.12"]
        fail-fast: false
  
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: install browsers
          run: |
              pip install playwright && playwright install chromium firefox
        
        - name: install dependencies
          run: |
            pip install -r requirements.txt

        - name: pytest unit tests
          run: |
            pytest

